services:
  discord-bot-loop:
    build:
      context: .
    image: discord-bot
    volumes:
      - ${DATA_PATH:-./data}:/app/data
    restart: unless-stopped
    environment:
      TZ: ${TIMEKPR_TZ:-America/Los_Angeles}
    command: "python ./loop_over_printers.py"
    tty: true
    stdin_open: true
  discord-bot:
    build:
      context: .
    image: discord-bot
    volumes:
      - ${DATA_PATH:-./data}:/app/data
    restart: unless-stopped
    environment:
      TZ: ${TIMEKPR_TZ:-America/Los_Angeles}
    depends_on:
      - discord-bot-loop
    tty: true
    stdin_open: true