
PHRASES = [
    "IS THE SHOP OPEN",
    "IS THE SHOP OPEN NOW",
    "WHEN IS THE SHOP OPEN",
    "SHOP HOURS",
    "IS ANYONE AT THE SHOP NOW",
    "IS ANY ONE AT THE SHOP NOW",
    "IS ANYONE AT THE SHOP",
    "IS ANY ONE AT THE SHOP",
    "IS ANYONE GOING TO BE AT THE SHOP TODAY",
    "IS ANY ONE GOING TO BE AT THE SHOP TODAY",
    "IS ANYONE GOING TO BE AT THE SHOP TOMORROW",
    "IS ANY ONE GOING TO BE AT THE SHOP TOMORROW",
    "IS ANYONE GOING TO BE AT THE SHOP TONIGHT",
    "IS ANY ONE GOING TO BE AT THE SHOP TONIGHT",
    "IS ANYONE GOING TO THE SHOP TONIGHT",
    "IS ANY ONE GOING TO THE SHOP TONIGHT",
    "IS ANYONE GOING TO THE SHOP TODAY",
    "IS ANY ONE GOING TO THE SHOP TODAY",
    "IS ANYONE GOING TO THE SHOP TOMORROW",
    "IS ANY ONE GOING TO THE SHOP TOMORROW",
    "ANY PLANS FOR THE SHOP TO BE OPEN",
    "ANYONE GOING TONIGHT",
    "ANY ONE GOING TONIGHT"
]

SHOP_HOURS_URL="https://synshop.org/hours/index.html"