
PHRASES = [
    "IS THE SHOP OPEN",
    "IS THE SHOP OPEN NOW",
    "IS ANYONE AT THE SHOP NOW",
    "IS ANY ONE AT THE SHOP NOW",
    "IS ANYONE AT THE SHOP",
    "IS ANY ONE AT THE SHOP",
    "IS ANYONE GOING TO BE AT THE SHOP TODAY",
    "IS ANY ONE GOING TO BE AT THE SHOP TODAY",
    "IS ANYONE GOING TO BE AT THE SHOP TOMORROW",
    "IS ANY ONE GOING TO BE AT THE SHOP TOMORROW",
    "IS ANYONE GOING TO BE AT THE SHOP TONIGHT",
    "IS ANY ONE GOING TO BE AT THE SHOP TONIGHT",
    "IS ANYONE GOING TO THE SHOP TONIGHT",
    "IS ANY ONE GOING TO THE SHOP TONIGHT",
    "IS ANYONE GOING TO THE SHOP TODAY",
    "IS ANY ONE GOING TO THE SHOP TODAY",
    "IS ANYONE GOING TO THE SHOP TOMORROW",
    "IS ANY ONE GOING TO THE SHOP TOMORROW",
    "ANY PLANS FOR THE SHOP TO BE OPEN",
    "ANYONE GOING TONIGHT",
    "ANY ONE GOING TONIGHT",
    "WHEN IS THE SHOP OPEN",
    "WHEN IS SOMEONE AT THE SHOP",
    "WHAT TIME ARE YOU GUYS OPEN",
    "WHAT ARE SHOP HOURS",
    "WHAT ARE THE SHOP HOURS",
    "WHAT HOURS ARE YOU OPEN",
    "WHAT ARE THE HOURS",
    "THE SHOP HOURS",
    "SHOP OPEN",
    "SHOP HOURS"
]

SHOP_ADDRESS = "5967 Harrison Dr\nLas Vegas, NV, 89120"
SHOP_HOURS_URL="https://synshop.org/hours/index.html"